#!/usr/bin/env bash

set -e
shopt -s globstar

echo 'Pulling...'
git pull
echo 'Compiling...'
./compile
echo 'Packaging...'
./package
echo 'Stopping...'
pkill MultiwebApp || true
echo 'Starting...'
./run-production
