package daniel.pokemon.model;

public enum Ability {
  ADAPTABILITY("Adaptability"),
  AFTERMATH("Aftermath"),
  AIR_LOCK("Air Lock"),
  ANALYTIC("Analytic"),
  ANGER_POINT("Anger Point"),
  ANTICIPATION("Anticipation"),
  ARENA_TRAP("Arena Trap"),
  BAD_DREAMS("Bad Dreams"),
  BATTLE_ARMOR("Battle Armor"),
  BIG_PECKS("Big Pecks"),
  BLAZE("Blaze"),
  CACOPHONY("Cacophony"),
  CHEEK_POUCH("Cheek Pouch"),
  CHLOROPHYLL("Chlorophyll"),
  CLEAR_BODY("Clear Body"),
  CLOUD_NINE("Cloud Nine"),
  COLOR_CHANGE("Color Change"),
  COMPOUNDEYES("Compoundeyes"),
  CONTRARY("Contrary"),
  CURSED_BODY("Cursed Body"),
  CUTE_CHARM("Cute Charm"),
  DAMP("Damp"),
  DARK_AURA("Dark Aura"),
  DEFEATIST("Defeatist"),
  DEFIANT("Defiant"),
  DOWNLOAD("Download"),
  DRIZZLE("Drizzle"),
  DROUGHT("Drought"),
  DRY_SKIN("Dry Skin"),
  EARLY_BIRD("Early Bird"),
  EFFECT_SPORE("Effect Spore"),
  FAIRY_AURA("Fairy Aura"),
  FILTER("Filter"),
  FLAME_BODY("Flame Body"),
  FLARE_BOOST("Flare Boost"),
  FLASH_FIRE("Flash Fire"),
  FLOWER_GIFT("Flower Gift"),
  FORECAST("Forecast"),
  FOREWARN("Forewarn"),
  FRIEND_GUARD("Friend Guard"),
  FRISK("Frisk"),
  FUR_COAT("Fur Coat"),
  GLUTTONY("Gluttony"),
  GUTS("Guts"),
  HARVEST("Harvest"),
  HEALER("Healer"),
  HEATPROOF("Heatproof"),
  HEAVY_METAL("Heavy Metal"),
  HONEY_GATHER("Honey Gather"),
  HUGE_POWER("Huge Power"),
  HUSTLE("Hustle"),
  HYDRATION("Hydration"),
  HYPER_CUTTER("Hyper Cutter"),
  ICE_BODY("Ice Body"),
  ILLUMINATE("Illuminate"),
  ILLUSION("Illusion"),
  IMMUNITY("Immunity"),
  IMPOSTER("Imposter"),
  INFILTRATOR("Infiltrator"),
  INNER_FOCUS("Inner Focus"),
  INSOMNIA("Insomnia"),
  INTIMIDATE("Intimidate"),
  IRON_BARBS("Iron Barbs"),
  IRON_FIST("Iron Fist"),
  JUSTIFIED("Justified"),
  KEEN_EYE("Keen Eye"),
  KLUTZ("Klutz"),
  LEAF_GUARD("Leaf Guard"),
  LEVITATE("Levitate"),
  LIGHT_METAL("Light Metal"),
  LIGHTNINGROD("Lightningrod"),
  LIMBER("Limber"),
  LIQUID_OOZE("Liquid Ooze"),
  MAGIC_BOUNCE("Magic Bounce"),
  MAGIC_GUARD("Magic Guard"),
  MAGMA_ARMOR("Magma Armor"),
  MAGNET_PULL("Magnet Pull"),
  MARVEL_SCALE("Marvel Scale"),
  MEGA_LAUNCHER("Mega Launcher"),
  MINUS("Minus"),
  MOLD_BREAKER("Mold Breaker"),
  MOODY("Moody"),
  MOTOR_DRIVE("Motor Drive"),
  MOXIE("Moxie"),
  MULTISCALE("Multiscale"),
  MULTITYPE("Multitype"),
  MUMMY("Mummy"),
  NATURAL_CURE("Natural Cure"),
  NO_GUARD("No Guard"),
  NORMALIZE("Normalize"),
  OBLIVIOUS("Oblivious"),
  OVERCOAT("Overcoat"),
  OVERGROW("Overgrow"),
  OWN_TEMPO("Own Tempo"),
  PARENTAL_BOND("Parental Bond"),
  PICKPOCKET("Pickpocket"),
  PICKUP("Pickup"),
  PLUS("Plus"),
  POISON_HEAL("Poison Heal"),
  POISON_POINT("Poison Point"),
  POISON_TOUCH("Poison Touch"),
  PRANKSTER("Prankster"),
  PRESSURE("Pressure"),
  PURE_POWER("Pure Power"),
  QUICK_FEET("Quick Feet"),
  RAIN_DISH("Rain Dish"),
  RATTLED("Rattled"),
  RECKLESS("Reckless"),
  REFRIGERATE("Refrigerate"),
  REGENERATOR("Regenerator"),
  RIVALRY("Rivalry"),
  ROCK_HEAD("Rock Head"),
  ROUGH_SKIN("Rough Skin"),
  RUN_AWAY("Run Away"),
  SAND_FORCE("Sand Force"),
  SAND_RUSH("Sand Rush"),
  SAND_STREAM("Sand Stream"),
  SAND_VEIL("Sand Veil"),
  SAP_SIPPER("Sap Sipper"),
  SCRAPPY("Scrappy"),
  SERENE_GRACE("Serene Grace"),
  SHADOW_TAG("Shadow Tag"),
  SHED_SKIN("Shed Skin"),
  SHEER_FORCE("Sheer Force"),
  SHELL_ARMOR("Shell Armor"),
  SHIELD_DUST("Shield Dust"),
  SIMPLE("Simple"),
  SKILL_LINK("Skill Link"),
  SLOW_START("Slow Start"),
  SNIPER("Sniper"),
  SNOW_CLOAK("Snow Cloak"),
  SNOW_WARNING("Snow Warning"),
  SOLAR_POWER("Solar Power"),
  SOLID_ROCK("Solid Rock"),
  SOUNDPROOF("Soundproof"),
  SPEED_BOOST("Speed Boost"),
  STALL("Stall"),
  STATIC("Static"),
  STEADFAST("Steadfast"),
  STENCH("Stench"),
  STICKY_HOLD("Sticky Hold"),
  STORM_DRAIN("Storm Drain"),
  STRONG_JAW("Strong Jaw"),
  STURDY("Sturdy"),
  SUCTION_CUPS("Suction Cups"),
  SUPER_LUCK("Super Luck"),
  SWARM("Swarm"),
  SWEET_VEIL("Sweet Veil"),
  SWIFT_SWIM("Swift Swim"),
  SYNCHRONIZE("Synchronize"),
  TANGLED_FEET("Tangled Feet"),
  TECHNICIAN("Technician"),
  TELEPATHY("Telepathy"),
  TERAVOLT("Teravolt"),
  THICK_FAT("Thick Fat"),
  TINTED_LENS("Tinted Lens"),
  TORRENT("Torrent"),
  TOUGH_CLAWS("Tough Claws"),
  TOXIC_BOOST("Toxic Boost"),
  TRACE("Trace"),
  TRUANT("Truant"),
  TURBOBLAZE("Turboblaze"),
  UNAWARE("Unaware"),
  UNBURDEN("Unburden"),
  UNNERVE("Unnerve"),
  VICTORY_STAR("Victory Star"),
  VITAL_SPIRIT("Vital Spirit"),
  VOLT_ABSORB("Volt Absorb"),
  WATER_ABSORB("Water Absorb"),
  WATER_VEIL("Water Veil"),
  WEAK_ARMOR("Weak Armor"),
  WHITE_SMOKE("White Smoke"),
  WONDER_GUARD("Wonder Guard"),
  WONDER_SKIN("Wonder Skin"),
  ZEN_MODE("Zen Mode"),
  ;

  private final String visibleName;

  private Ability(String visibleName) {
    this.visibleName = visibleName;
  }

  @Override
  public String toString() {
    return visibleName;
  }
}
