#!/usr/bin/env bash

set -e
shopt -s globstar

echo 'Compiling...'
rm -rf manual_out
mkdir -p manual_out
find . | grep '.java$' | grep -v 'Test.java$' | xargs javac -cp 'lib/*' -d manual_out

echo 'Packaging...'
rm -f all.jar
cd manual_out
version=$(git rev-parse --verify HEAD)
echo "Implementation-Version: $version" > manifest-extras
jar cmf manifest-extras ../all.jar **/*.class
rm manifest-extras

echo 'Done.'
