#!/usr/bin/env bash

set -e
shopt -s globstar

if [[ $UID != 0 ]]; then
  echo 'Run with sudo.'
  exit 1
fi

export ENVIRONMENT=production
java -cp "all.jar:lib/*" daniel.multiweb.MultiwebApp 2>&1 | tee -a multiweb.log
