#!/usr/bin/env bash

set -e

old_head=$(git rev-parse --verify HEAD)
git pull -q
new_head=$(git rev-parse --verify HEAD)

if [ "$new_head" != "$old_head" ]; then
  echo "Pulled new version: $new_head."
  script/compile
  script/restart-daemon
else
  echo 'No new changes.'
fi
