#!/usr/bin/env bash

if [[ $UID != 0 ]]; then
  echo "Run with sudo."
  exit 1
fi

echo -n 'Stopping daemon.'

pkill -f MultiwebApp
while pgrep -f MultiwebApp >/dev/null; do
  sleep 1
  echo -n '.'
done

echo
